#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "RUNNING THE DEPLOY HOOK"

app_name='takedown'

if [ -n "${OPENSHIFT_GEAR_DNS:+x}" ]; then

    ln -s $OPENSHIFT_REPO_DIR/nodematch $OPENSHIFT_REPO_DIR/wsgi/wrestling/static
    echo "var BASEURL='https://${OPENSHIFT_GEAR_DNS}'" > $OPENSHIFT_REPO_DIR/wsgi/wrestling/static/js/base_url.js 
fi
