#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "RUNNING THE DEPLOY HOOK"


if ["$OPENSHIFT_GEAR_NAME" = "takedownui"]
    cp -r $OPENSHIFT_REPO_DIR/nodematch/* $HOME/app-root/repo/diy

    echo "var BASEURL='https://takedownRest-tresback.rhcloud.com'" > $HOME/app-root/repo/diy/js/base_url.js 
fi
