#!/usr/bin/env python
import os
virtenv = os.environ['OPENSHIFT_HOMEDIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from wrestling import app as application
