import json
import requests
from string import Template

raw_schools = [
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Easley High School',
            city='Easley',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Greenwood High School',
            city='Greenwood',
            county='Greenwood',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Hillcrest High School',
            city='Simpsonville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='JL Mann High School',
            city='Greenville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Laurens District 55 High School',
            city='Laurens',
            county='Laurens',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='TL Hanna High School',
            city='Anderson',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Westside High School',
            city='Anderson',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region I',
            school_name='Woodmont High School',
            city='Piedmont',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Boiling Springs High School',
            city='Boiling Springs',
            county='Spartanburg',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Byrnes High School',
            city='Duncan',
            county='Spartanburg',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Dorman High School',
            city='Spartanburg',
            county='Spartanburg',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Gaffney High School',
            city='Gaffney',
            county='Cherokee',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Mauldin High School',
            city='Mauldin',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Riverside High School',
            city='Greer',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Spartanburg High School',
            city='Spartanburg',
            county='Spartanburg',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='4A',
            conference='Region II',
            school_name='Wade Hampton High School',
            city='Greenville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Seneca High School',
            city='Seneca',
            county='Oconee',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Belton-Honea Path High School',
            city='Honea Path',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Daniel High School',
            city='Central',
            county='Pickens',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Emerald High School',
            city='Greenwood',
            county='Greenwood',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Palmetto High School',
            city='Williamston',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Walhalla High School',
            city='Walhalla',
            county='Oconee',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='West Oak High School',
            city='Westminster',
            county='Oconee',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region I',
            school_name='Wren High School',
            city='Piedmont',
            county='Anderson',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Berea High School',
            city='Greenville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Blue Ridge High School',
            city='Greer',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Eastside High School',
            city='Taylors',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Greenville High School',
            city='Greenville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Greer High School',
            city='Greer',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Pickens High School',
            city='Pickens',
            county='Pickens',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Southside High School',
            city='Greenville',
            county='Greenville',
            wrestlers=[]),
        dict(
            competition='High School',
            area='SC',
            size='3A',
            conference='Region II',
            school_name='Travelers Rest High School',
            city='Travelers Rest',
            county='Greenville',
            wrestlers=[])
        ]
         

def create_school(school):
    url = Template('http://local.tresback.rhcloud.com:5001/$competition/$area/$size/$conference/$school_name').substitute(school)
    requests.put(url, data=json.dumps(school))


if __name__ == '__main__':
    [create_school(school) for school in raw_schools]

